### ISSUE TITLE
There are no mention about what uniprot_csv is .

### ISSUE THREAD

**Issue by ven-kyoshiro** [igemsoftware2017/AiGEM_TeamHeidelberg2017#1]
DeeProtain is very cool research and I cloned this repository to test your code.
I read README but I didn't understand what uniprot_csv is.
Let me know, what is uniprot_csv and how to download it.

**Comment by thbuerg** [comment]
Hi,

sorry for the confusion!
 
uniprot.csv is a csv file used as input to the pipeline generating the datasets. It is obtained by parsing the uniprot.txt file (the flat text download from uniprot). The `process_data.py` script handles that. Defined is the function in the `DatasetGenerator` class, which has a method `uniprot_to_csv`.

Hope that helped!
